In [1]:
from alntk.alignment import Alignment, filter_residues, delete_bjxz, compactify

In [2]:
import numpy as np

In [3]:
aln = Alignment()

In [4]:
aln.import_from_fasta('../data/new_aln0.faa')

In [5]:
aln.print_report()

Number of sequences: 189304
Number of positions: 823


In [10]:
filter_residues(aln, 'TRY2_RAT', 'IVGG')[0].shape

(61612,)

In [11]:
delete_bjxz(aln)

(array([   326,    327,    328, ..., 188810, 188828, 189055]), [])

In [7]:
aln_seqs = aln.get_seqs()

# Boh

In [7]:
aln_seqs = aln.get_seqs()

In [8]:
def find_pattern(text, pattern):
    """
    """
    pattern = np.asarray(list(pattern))
    
    if len(pattern) > len(text):
        return np.array([], dtype=int)
    
    # Create sliding window view of text
    windows = np.lib.stride_tricks.as_strided(
        text, 
        shape=(len(text) - len(pattern) + 1, len(pattern)),
        strides=(text.strides[0], text.strides[0])
    )
    
    # Find indices where windows match the pattern
    match_indices = np.where(np.all(windows == pattern, axis=1))[0]
    
    return match_indices

In [10]:
aln_descs = aln.get_descs()

In [12]:
np.where(np.array([e.split('|')[2] for e in aln_descs]) == 'TRY2_RAT')

(array([10986]),)

In [15]:
find_pattern(aln_seqs[10986], 'IVGG')

array([130])

In [19]:
np.sum(aln_seqs[:, 130:134] == '-', axis=1)

array([0, 0, 0, ..., 4, 4, 4])